enmasse:

  iot:

    vertx:
      preferNative: true

    tenant:

      app:
        maxInstances: 1
        healthCheckBindAddress: 0.0.0.0
        healthCheckPort: 8088

      endpoint:
        amqp:
          port: 5671

  auth:
    host: ${hono.auth.host}
    port: 5671
    keyPath: ${secret.path}/device-registry-key.pem
    certPath: ${secret.path}/device-registry-cert.pem
    trustStorePath: ${secret.path}/trusted-certs.pem
    name: 'Hono Device Registry'
    validation:
      certPath: ${secret.path}/auth-server-cert.pem
