enmasse:
  iot:

    tenant:

      endpoint:

        amqp:
          insecurePortEnabled: true
          insecurePort: 15672

        http:
          insecurePortEnabled: true
          insecurePort: 18080
