enmasse:
  iot:

    auth:
      validation:
        sharedSecret: 1234567890123456789012345678901234567890123456789012345678901234

    tenant:

      endpoint:

        amqp:
          insecurePortEnabled: true
          insecurePort: 15672

        http:
          insecurePortEnabled: true
          insecurePort: 18080
