---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hono-qdr-configurator
rules:
- apiGroups:
  - iot.enmasse.io
  resources:
  - iotprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
