kind: ConfigMap
apiVersion: v1
metadata:
  name: hono-service-device-registry-config
  labels:
    app: iot-registry
    component: hono-service-device-registry
    enmasse-component: iot
data:
  application.yml: |+
    hono:
      app:
        maxInstances: 1
        healthCheckBindAddress: 0.0.0.0
        healthCheckPort: 8088
      auth:
        port: 5671
        keyPath: /etc/tls/tls.key
        certPath: /etc/tls/tls.crt
        keyFormat: PEM
        trustStorePath: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        trustStoreFormat: PEM
        name: 'Hono Device Registry'
        validation:
          certPath: /etc/tls-auth-service/tls.crt
      registry:
        amqp:
          bindAddress: 0.0.0.0
          keyPath: /etc/tls/tls.key
          certPath: /etc/tls/tls.crt
          keyFormat: PEM
        rest:
          bindAddress: 0.0.0.0
          keyPath: /etc/tls/tls.key
          certPath: /etc/tls/tls.crt
          keyFormat: PEM
        svc:
          filename: /var/lib/hono/device-registry/device-identities.json
          saveToFile: true
      credentials:
        svc:
          credentialsFilename: /var/lib/hono/device-registry/credentials.json
          saveToFile: true
      tenant:
        svc:
          filename: /var/lib/hono/device-registry/tenants.json
          saveToFile: true
      metrics:
        legacy: false
    management:
      metrics:
        enabled: false
        export:
          graphite:
            enabled: false

  logback-spring.xml: |+
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE xml>

      <configuration>

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
          <!-- encoders are assigned the type
               ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
          <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
          </encoder>
        </appender>

        <root level="INFO">
          <appender-ref ref="STDOUT" />
        </root>

        <springProfile name="dev">
          <logger name="org.eclipse.hono.client" level="DEBUG"/>
          <logger name="org.eclipse.hono.connection" level="DEBUG"/>
          <logger name="org.eclipse.hono.deviceregistry" level="DEBUG"/>
          <logger name="org.eclipse.hono.service" level="DEBUG"/>

          <logger name="io.netty.handler.logging.LoggingHandler" level="DEBUG"/>
          <logger name="io.netty.resolver.dns" level="INFO"/>

          <logger name="io.vertx.proton.impl" level="INFO"/>
          <logger name="io.vertx.core.net.impl" level="INFO"/>
        </springProfile>

        <springProfile name="prod">
          <logger name="org.eclipse.hono" level="INFO"/>

          <logger name="io.netty.handler.logging.LoggingHandler" level="INFO"/>
          <logger name="io.netty.resolver.dns" level="INFO"/>

          <logger name="io.vertx.proton.impl" level="INFO"/>
          <logger name="io.vertx.core.net.impl" level="INFO"/>
        </springProfile>

      </configuration>