kind: Secret
apiVersion: v1
metadata:
  name: iot-http-adapter-secrets
  labels:
    app: iot-http-adapter
    enmasse-component: iot
stringData:
  registry.properties: |-
    username: http-adapter@HONO
    password: http-secret
