apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iotprojects.iot.enmasse.io
spec:
  group: iot.enmasse.io
  version: v1alpha1
  names:
    kind: IoTProject
    plural: iotprojects
    singular: iotproject
    shortNames:
    - itp
  scope: Namespaced
