kind: ImageStream
apiVersion: v1
metadata:
  name: fabric8-s2i-java
spec:
  tags:
  - from:
      kind: DockerImage
      name: fabric8/s2i-java:2.3
    importPolicy:
      scheduled: true
    name: "2.3"
    referencePolicy:
      type: Source