---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iotprojects.iot.enmasse.io
spec:
  group: iot.enmasse.io
  version: v1alpha1
  names:
    kind: IoTProject
    plural: iotprojects
    singular: iotproject
    shortNames:
    - itp
  scope: Namespaced
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: iot-project-configurator
rules:
  - apiGroups:
    - iot.enmasse.io
    resources:
    - iotprojects
    verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups: [ "enmasse.io" ]
    resources: [ "addresses", "addressspaces" ]
    verbs: [ "create", "get", "update", "delete", "list", "watch", "patch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iot-project-configurator-hono-project
roleRef:
  kind: ClusterRole
  name: iot-project-configurator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: ${NAMESPACE}
  name: default
