kind: ImageStream
apiVersion: v1
metadata:
  name: qdrouterd-base
spec:
  tags:
  - from:
      kind: DockerImage
      name: enmasseproject/qdrouterd-base:1.4.1
    importPolicy:
      scheduled: true
    name: "1.4.1"
    referencePolicy:
      type: Source  