---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iotprojects.iot.enmasse.io
spec:
  group: iot.enmasse.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: iotprojects
    singular: iotproject
    kind: IoTProject
    shortNames:
      - iot
  validation:
    openAPIV3Schema:
      required: ["spec"]
