kind: ConfigMap
apiVersion: v1
metadata:
  name: iot-tenant-service
  labels:
    app: iot-tenant-service
    enmasse-component: iot
data:
  logback-spring.xml: |+
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE xml>
        
        <configuration>
        
          <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
              <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
          </appender>
        
          <root level="INFO">
            <appender-ref ref="STDOUT" />
          </root>
          
          <logger name="org.eclipse.hono" level="INFO"/>
        
        </configuration>
