kind: DeploymentConfig
apiVersion: v1
metadata:
  name: iot-tenant-service
  labels:
    app: iot-registry
    deploymentconfig: iot-tenant-service
    enmasse-component: iot
spec:
  replicas: 1
  selector:
    app: iot-registry
    deploymentconfig: iot-tenant-service
  strategy:
    type: Rolling
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - tenant-service
        from:
          kind: ImageStreamTag
          name: iot-tenant-service:latest
  template:
    metadata:
      labels:
        app: iot-registry
        deploymentconfig: iot-tenant-service
    spec:
      containers:
      - name: tenant-service
        image: iot-tenant-service
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: LOGGING_CONFIG
          value: file:///etc/config/logback-spring.xml
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENMASSE_IOT_AUTH_HOST
          value: hono-service-auth.$(KUBERNETES_NAMESPACE).svc
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 180
        resources:
          limits:
            memory: 512Mi
        ports:
        - name: jolokia
          containerPort: 8778 
        - name: health
          containerPort: 8088
        - name: service
          containerPort: 8080
        - name: actuator
          containerPort: 8081
        - name: amqps
          containerPort: 5671
        volumeMounts:
        - mountPath: /etc/config
          name: conf
        - mountPath: /etc/tls
          name: tls
          readOnly: true
        - mountPath: /etc/tls-auth-service
          name: tls-auth-service
          readOnly: true
      volumes:
      - name: conf
        configMap:
          name: iot-tenant-service
      - name: tls
        secret:
          secretName: iot-tenant-service-tls
      - name: tls-auth-service
        secret:
          secretName: hono-service-auth-tls
