kind: DeploymentConfig
apiVersion: v1
metadata:
  name: iot-tenant-service
  labels:
    app: iot-tenant-service
    deploymentconfig: iot-tenant-service
spec:
  replicas: 1
  selector:
    app: iot-tenant-service
    deploymentconfig: iot-tenant-service
  strategy:
    type: Rolling
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - tenant-service
        from:
          kind: ImageStreamTag
          name: iot-tenant-service:latest
  template:
    metadata:
      labels:
        app: iot-tenant-service
        deploymentconfig: iot-tenant-service
    spec:
      containers:
      - name: tenant-service
        image: iot-tenant-service
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: LOGGING_CONFIG
          value: file:///etc/config/logback-spring.xml
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 180
        resources:
          limits:
            memory: 512Mi
        ports:
        - containerPort: 8778 
          name: jolokia
        - containerPort: 8088
          name: health
        - containerPort: 8080
          name: service
        - name: actuator
          port: 8081
        volumeMounts:
        - mountPath: /etc/config
          name: conf
        - mountPath: /etc/tls
          name: tls
          readOnly: true
      volumes:
      - name: conf
        configMap:
          name: iot-tenant-service
      - name: tls
        secret:
          secretName: iot-tenant-service-tls
