kind: Secret
apiVersion: v1
metadata:
  name: iot-mqtt-adapter-secrets
  labels:
    app: iot-mqtt-adapter
    enmasse-component: iot
stringData:
  registry.properties: |-
    username: mqtt-adapter@HONO
    password: mqtt-secret
