---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hono-service-auth-config
  labels:
    app: enmasse
    component: hono-service-auth
data:
  application.yml: |+
    hono:
      app:
        maxInstances: 1
      auth:
        amqp:
          bindAddress: 0.0.0.0
          keyPath: /etc/tls/tls.key
          certPath: /etc/tls/tls.crt
          keyFormat: PEM
          trustStorePath: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          trustStoreFormat: PEM
          insecurePortEnabled: true
          insecurePortBindAddress: 0.0.0.0
        svc:
          permissionsPath: file:///etc/config/permissions.json
      metrics:
        legacy: false
    management:
      metrics:
        enabled: false
        export:
          graphite:
            enabled: false

  permissions.json: |+
    {
      "roles": {
        "protocol-adapter": [
          {
            "resource": "telemetry/*",
            "activities": [ "WRITE" ]
          },
          {
            "resource": "event/*",
            "activities": [ "WRITE" ]
          },
          {
            "resource": "registration/*",
            "activities": [ "READ", "WRITE" ]
          },
          {
            "operation": "registration/*:assert",
            "activities": [ "EXECUTE" ]
          },
          {
            "resource": "credentials/*",
            "activities": [ "READ", "WRITE" ]
          },
          {
            "operation": "credentials/*:get",
            "activities": [ "EXECUTE" ]
          },
          {
            "resource": "tenant",
            "activities": [ "READ", "WRITE" ]
          },
          {
            "operation": "tenant/*:*",
            "activities": [ "EXECUTE" ]
          }
        ],
        "device-manager": [
          {
            "resource": "registration/*",
            "activities": [ "READ", "WRITE" ]
          },
          {
            "operation": "registration/*:*",
            "activities": [ "EXECUTE" ]
          }
        ],
        "consumer": [
          {
            "resource": "telemetry/*",
            "activities": [ "READ" ]
          },
          {
            "resource": "event/*",
            "activities": [ "READ" ]
          }
        ]
      },
      "users": {
        "amqp-adapter@HONO": {
          "mechanism": "PLAIN",
          "password": "amqp-secret",
          "authorities": [ "hono-component", "protocol-adapter" ]
        },
        "http-adapter@HONO": {
          "mechanism": "PLAIN",
          "password": "http-secret",
          "authorities": [ "hono-component", "protocol-adapter" ]
        },
        "mqtt-adapter@HONO": {
          "mechanism": "PLAIN",
          "password": "mqtt-secret",
          "authorities": [ "hono-component", "protocol-adapter" ]
        },
        "kura-adapter@HONO": {
          "mechanism": "PLAIN",
          "password": "kura-secret",
          "authorities": [ "hono-component", "protocol-adapter" ]
        },
        "hono-client@HONO": {
          "mechanism": "PLAIN",
          "password": "secret",
          "authorities": [ "protocol-adapter", "device-manager" ]
        },
        "hono-messaging": {
          "mechanism": "EXTERNAL",
          "authorities": []
        },
        "device-registry": {
          "mechanism": "EXTERNAL",
          "authorities": []
        }
      }
    }

  logback-spring.xml: |+
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE xml>

      <configuration>

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
          <!-- encoders are assigned the type
               ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
          <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
          </encoder>
        </appender>

        <root level="INFO">
          <appender-ref ref="STDOUT" />
        </root>

        <springProfile name="dev">
          <logger name="org.eclipse.hono.service" level="DEBUG"/>

          <logger name="io.netty.handler.logging.LoggingHandler" level="DEBUG"/>

          <logger name="io.vertx.proton.impl" level="INFO"/>
          <logger name="io.vertx.core.net.impl" level="INFO"/>
        </springProfile>

        <springProfile name="prod">
          <logger name="org.eclipse.hono" level="INFO"/>

          <logger name="io.netty.handler.logging.LoggingHandler" level="INFO"/>

          <logger name="io.vertx.proton.impl" level="INFO"/>
          <logger name="io.vertx.core.net.impl" level="INFO"/>
        </springProfile>

      </configuration>
