---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: iot-core
    component: hono-service-auth
    enmasse-component: iot
  name: hono-service-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-core
      component: hono-service-auth
  template:
    metadata:
      labels:
        app: iot-core
        component: hono-service-auth
    spec:
      containers:
      - image: eclipse/hono-service-auth:${HONO_VERSION}
        imagePullPolicy: IfNotPresent
        name: eclipse-hono-service-auth
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:///etc/config/
        - name: SPRING_PROFILES_ACTIVE
          value: authentication-impl
        - name: LOGGING_CONFIG
          value: file:///etc/config/logback-spring.xml
#        - name: HONO_AUTH_SVC_SIGNING_SHARED_SECRET
#          valueFrom:
#            secretKeyRef:
#              name: hono-secrets
#              key: shared.signing.secret
#        - name: HONO_AUTH_SVC_VALIDATION_SHARED_SECRET
#          valueFrom:
#            secretKeyRef:
#              name: hono-secrets
#              key: shared.signing.secret
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
#        - name: AB_JOLOKIA_USER
#          value: jolokia
#        - name: AB_JOLOKIA_PASSWORD_RANDOM
#          value: "false"
#        - name: AB_JOLOKIA_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: hono-secrets
#              key: jolokia.password
        livenessProbe:
          initialDelaySeconds: 25
          periodSeconds: 9
          tcpSocket:
            port: 5672
          timeoutSeconds: 1
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          tcpSocket:
            port: 5672
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        ports:
        - containerPort: 8778
          name: jolokia
        - containerPort: 5671
          name: amqps
          protocol: TCP
        - containerPort: 5672
          name: amqp
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/config
          name: conf
        - mountPath: /etc/tls
          name: tls
          readOnly: true
      volumes:
      - name: conf
        configMap:
          name: hono-service-auth-config
      - name: tls
        secret:
          secretName: hono-service-auth-tls